# Generated by Django 5.1.6 on 2025-02-10 09:33

from django.contrib.postgres import operations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('world', '0001_initial'),]
    operations = [
        operations.CreateExtension('postgis'),
    ]
