"""New fields were added to User model

Revision ID: 210f89ccc953
Revises: 8fa9c781965f
Create Date: 2024-12-14 14:30:02.280897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210f89ccc953'
down_revision: Union[str, None] = '8fa9c781965f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))

    # Create the genderenum type
    genderenum = sa.Enum('male', 'female', name='genderenum')
    genderenum.create(op.get_bind(), checkfirst=True)

    # Alter the gender column to use the genderenum type with USING clause
    op.execute("""ALTER TABLE users ALTER COLUMN gender TYPE genderenum USING gender::genderenum""")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=sa.Enum('male', 'female', name='genderenum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_staff')
    # ### end Alembic commands ###
