"""added light icon svg

Revision ID: abfb9337f0ce
Revises: d4ccd837f612
Create Date: 2025-02-11 12:59:51.667767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abfb9337f0ce'
down_revision: Union[str, None] = 'd4ccd837f612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spheres', sa.Column('icon_light', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spheres', 'icon_light')
    # ### end Alembic commands ###
