"""Section ID

Revision ID: d4ccd837f612
Revises: fe90bbc963f8
Create Date: 2024-12-23 10:57:43.078656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4ccd837f612'
down_revision: Union[str, None] = 'fe90bbc963f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spheres', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_spheres_section_id'), 'spheres', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spheres_section_id'), table_name='spheres')
    op.drop_column('spheres', 'section_id')
    # ### end Alembic commands ###
