# Generated by Django 4.2.14 on 2024-07-26 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evcharginglocation',
            name='altitude',
        ),
    ]
