# Generated by Django 4.2.14 on 2024-10-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_remove_evcharginglocation_altitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(default='Feature', max_length=20)),
                ('properties', models.JSONField()),
                ('geometry', models.JSONField()),
            ],
            options={
                'verbose_name': 'Geo Feature',
                'verbose_name_plural': 'Geo Features',
                'db_table': 'geo_features',
            },
        ),
    ]
