"""Indexing parent

Revision ID: 0d003d8b9723
Revises: abfb9337f0ce
Create Date: 2025-05-08 14:20:52.401044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d003d8b9723'
down_revision: Union[str, None] = 'abfb9337f0ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_spheres_parent_id'), 'spheres', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spheres_parent_id'), table_name='spheres')
    # ### end Alembic commands ###
